crudteste/config/routes.rb
Rails.application.routes.draw do
  resources :crudetes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

crudteste/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crudteste/app/models/crudete.rb
class Crudete < ApplicationRecord
end

crudteste/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

crudteste/app/controllers/crudetes_controller.rb
class CrudetesController < ApplicationController
  before_action :set_crudete, only: [:show, :edit, :update, :destroy]

  # GET /crudetes
  # GET /crudetes.json
  def index
    @crudetes = Crudete.all
  end

  # GET /crudetes/1
  # GET /crudetes/1.json
  def show
  end

  # GET /crudetes/new
  def new
    @crudete = Crudete.new
  end

  # GET /crudetes/1/edit
  def edit
  end

  # POST /crudetes
  # POST /crudetes.json
  def create
    @crudete = Crudete.new(crudete_params)

    respond_to do |format|
      if @crudete.save
        format.html { redirect_to @crudete, notice: 'Crudete was successfully created.' }
        format.json { render :show, status: :created, location: @crudete }
      else
        format.html { render :new }
        format.json { render json: @crudete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crudetes/1
  # PATCH/PUT /crudetes/1.json
  def update
    respond_to do |format|
      if @crudete.update(crudete_params)
        format.html { redirect_to @crudete, notice: 'Crudete was successfully updated.' }
        format.json { render :show, status: :ok, location: @crudete }
      else
        format.html { render :edit }
        format.json { render json: @crudete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crudetes/1
  # DELETE /crudetes/1.json
  def destroy
    @crudete.destroy
    respond_to do |format|
      format.html { redirect_to crudetes_url, notice: 'Crudete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crudete
      @crudete = Crudete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crudete_params
      params.require(:crudete).permit(:nome, :email)
    end
end

crudteste/app/helpers/application_helper.rb
module ApplicationHelper
end

crudteste/app/helpers/crudetes_helper.rb
module CrudetesHelper
end

crudteste/app/views/crudetes/_form.html.erb
<%= form_with(model: crudete, local: true) do |form| %>
  <% if crudete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crudete.errors.count, "error") %> prohibited this crudete from being saved:</h2>

      <ul>
      <% crudete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

crudteste/app/views/crudetes/edit.html.erb
<h1>Editing Crudete</h1>

<%= render 'form', crudete: @crudete %>

<%= link_to 'Show', @crudete %> |
<%= link_to 'Back', crudetes_path %>

crudteste/app/views/crudetes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crudetes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crudetes.each do |crudete| %>
      <tr>
        <td><%= crudete.nome %></td>
        <td><%= crudete.email %></td>
        <td><%= link_to 'Show', crudete %></td>
        <td><%= link_to 'Edit', edit_crudete_path(crudete) %></td>
        <td><%= link_to 'Destroy', crudete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crudete', new_crudete_path %>

crudteste/app/views/crudetes/new.html.erb
<h1>New Crudete</h1>

<%= render 'form', crudete: @crudete %>

<%= link_to 'Back', crudetes_path %>

crudteste/app/views/crudetes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @crudete.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @crudete.email %>
</p>

<%= link_to 'Edit', edit_crudete_path(@crudete) %> |
<%= link_to 'Back', crudetes_path %>

crudteste/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crudteste</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>